In [1]:
import seaborn as sns

In [2]:
df=sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [7]:
df.dropna().shape

(182, 15)

In [8]:
df.dropna(axis=1,inplace=True)

##imputation missing values

In [12]:
df=sns.load_dataset('titanic')

In [15]:
df['age_mean']=df['age'].fillna(df['age'].mean())

In [16]:
df[['age','age_mean']]

      age   age_mean
0    22.0  22.000000
1    38.0  38.000000
2    26.0  26.000000
3    35.0  35.000000
4    35.0  35.000000
..    ...        ...
886  27.0  27.000000
887  19.0  19.000000
888   NaN  29.699118
889  26.0  26.000000
890  32.0  32.000000

[891 rows x 2 columns]

##mean imputation works when data is normally distributed

###median value imputation if we have outliers in the dataset

In [17]:
df['age_median']=df['age'].fillna(df['age'].median())

In [18]:
df[['age','age_median']]

      age  age_median
0    22.0        22.0
1    38.0        38.0
2    26.0        26.0
3    35.0        35.0
4    35.0        35.0
..    ...         ...
886  27.0        27.0
887  19.0        19.0
888   NaN        28.0
889  26.0        26.0
890  32.0        32.0

[891 rows x 2 columns]

mode imputation technique for catorigical data

In [19]:
df[df['embarked'].isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_median,age_mean
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,38.0,38.0
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,62.0,62.0

In [20]:
df['embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [25]:
mode_value=df['embarked'].mode()

In [26]:
df['embarked_mode'] = df['embarked'].fillna(mode_value)

In [27]:
df[['embarked_mode', 'embarked']]

    embarked_mode embarked
0               S        S
1               C        C
2               S        S
3               S        S
4               S        S
..            ...      ...
886             S        S
887             S        S
888             S        S
889             C        C
890             Q        Q

[891 rows x 2 columns]