One-Hot Encoding  

One-Hot Encoding is a method of converting categorical variables into multiple binary columns, where only the matching category is marked as 1 and all other categories are marked as 0.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [3]:
encoder=OneHotEncoder()

print("Original DataFrame:")
print(df)

Original DataFrame:
   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [4]:
# Perform One-Hot Encoding
encoded = encoder.fit_transform(df[['color']]).toarray()

In [5]:
encoder_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out()
)

In [6]:
print("\nEncoded DataFrame:")
print(encoder_df)

Encoded DataFrame:
   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

#HOMEWORK

In [8]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder=OneHotEncoder()

In [10]:
encoded = encoder.fit_transform(df[['sex']]).toarray()

In [11]:
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['sex'])
)

encoded_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]